config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help",       to: "static_pages#help"
  get "/contact",    to: "static_pages#contact"
  get "/policy",     to: "static_pages#policy"
  get "/signup",     to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get "/post",       to: "microposts#show"
  get "search" => "searches#search"

  resources :users, param: :id
  resources :microposts
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :micropost

  validates :user_id, presence: true
  validates :micropost_id, presence: true
  validates :user_id, uniqueness: { scope: :micropost_id, message: "has already favorited this post" }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  #投稿一覧に順序をつける（ラムダ記法）
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  def favorited_by?(user)
    favorited_by.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_microposts, through: :favorites, source: :micropost
  # メールアドレスをバリデーション前に全て小文字に変換するコールバック
  before_create { email.downcase! }
  before_create :set_id_digest #save後に呼び出される
  #presence: trueは空打ち禁止用
  validates :name, presence: true, length: { maximum: 50 }
  # メールの正規表現を定義
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password

  def to_param
    id_digest
  end

  def favorite(micropost)
    favorites.create(micropost: micropost) unless favorite?(micropost)
  end

  def unfavorite(micropost)
    favorites.find_by(micropost: micropost)&.destroy
  end

  def favorite?(micropost)
    favorite_microposts.include?(micropost)
  end

  def self.find_by_id_digest(id_digest)
    find_by(id_digest: id_digest)
  end

  private

  def set_id_digest
    self.id_digest = SecureRandom.urlsafe_base64 while id_digest.nil? || User.exists?(id_digest: id_digest)
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper

  before_action :search

    def search
      @q = Micropost.ransack(params[:q])
      @item = @q.result(distinct: true)
      @result = params[:q]&.values&.reject(&:blank?)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

   def create
    @micropost = Micropost.find(params[:micropost_id])
    current_user.favorite(@micropost)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @micropost }
    end
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    current_user.unfavorite(@micropost)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @micropost }
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
before_action :set_params, only: [:show, :edit, :destroy, :update]
before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  def index
    @posts = Micropost.page(params[:page])
  end

  def new
    @post = Micropost.new
  end

  def create
    @post = current_user.microposts.build(micropost_params)
    if @post.save
      redirect_to @post, notice: '投稿が作成されました。'
    else
      flash.now[:alert] = '投稿に失敗しました。'
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(micropost_params)
      flash[:notice] = "変更を保存しました。"
      redirect_to @post
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    flash.notice = "投稿を削除しました。"
    redirect_to microposts_url

  end

  private

  def set_params
    @post = Micropost.find(params[:id])
  end

  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #User.find_byメソッドはアクティブレコードが提供
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      #判定後、セッション情報をリセットし、再セットする。セキュリティの為
      reset_session
      log_in @user
      redirect_to @user
    else
      flash[:denger] = "メールアドレス又は、パスワードが正しくありません。"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def show
    # 　Viewから与えられた引数をもとにUsersテーブルの該当レコードを検索し、変数に格納
    @user = User.find_by!(id_digest: params[:id])
  end

  def new
    #  Userクラスのオブジェクトを作成して、viewに渡す
    @user = User.new
  end

  def create
    #  多分ストロングパラメーター為に書いてるぽい、セキュリティかな
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = 'ログインしました。'
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find_by_id_digest(params[:id])
  end

  def update
    @user = User.find_by_id_digest(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find_by_id_digest(params[:id]).destroy
    flash[:success] = "アカウントを削除しました。"
    redirect_to root_url, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #ページタイトルが定義されていない場合は、base_titleを出力する
  def full_title(page_title = '')
    base_title = "基本情報フィードバックサイトFE_FD"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def turbo_stream_flash
    turbo_stream.append "flashes", partial: "flash"
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #rails定義メソッドのsessionを使ってcookiesに暗号化したユーザーIDが作成される
  def log_in(user)
    session[:user_id_digest] = user.id_digest
  end

    # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    @current_user ||= User.find_by(id_digest: session[:user_id_digest]) if session[:user_id_digest]
  end

  #  ログインしていればtrue,その他ならfalseを返す。
  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper


  private
    def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to login_url, status: :see_other
    end
  end

  def correct_user
    @user = User.find_by_id_digest(params[:id])
    redirect_to(root_url, status: :see_other) unless @user == current_user
  end

end

app/views/application/_flash.html.erb
<div class="flash-container">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show flash-message" role="alert" data-controller="flash">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/favorites/_favorite.html.erb
<% if logged_in? %>
  <%= turbo_frame_tag dom_id(post, :favorite) do %>
    <% favorited = post.favorited_by?(current_user) %>
    <% method = favorited ? :delete : :post %>
    <% path = micropost_favorites_path(post) %>
    <%= button_to path, method: method, data: { turbo_frame: dom_id(post, :favorite) }, class: "btn btn-light" do %>
      <i class="fas fa-heart text-lg" aria-hidden="true" style="<%= 'color: red;' if favorited %>"></i>
      <%= post.favorites.count %>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(@micropost, :favorite) do %>
  <%= render partial: 'favorites/favorite', locals: { post: @micropost } %>
<% end %>

app/views/favorites/destroy.turbo_stream.erb
<%= turbo_stream.replace dom_id(@micropost, :favorite) do %>
  <%= render partial: 'favorites/favorite', locals: { post: @micropost } %>
<% end %>

app/views/layouts/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide text-center">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "computer_tokui_boy.png", alt: "", class: "d-block w-50" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "computer_tokui_boy.png", alt: "", class: "d-block w-50" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "computer_tokui_boy.png", alt: "", class: "d-block w-50" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <nav class='mx-auto'>
    <%=link_to image_tag('FE_ED.png', class: "icon"), root_path %>
    <ul>
      <ol><%= link_to "利用規約", help_path %></ol>
      <ol><%= link_to "プライバシーポリシー", policy_path %></ol>
      <ol><%= link_to "お問い合わせ", contact_path %></ol>
    </ul>
  </nav>
</footer>

app/views/layouts/_form.html.erb
    <%= bootstrap_form_with(model: @user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.text_field :name, label: "名前" %>

      <%= f.email_field :email, label: "メールアドレス" %>

      <%= f.password_field :password, label: "パスワード" %>

      <%= f.password_field :password_confirmation, label: "パスワード再確認" %>

      <%= f.primary("登録") %>
    <% end %>

app/views/layouts/_header.html.erb
<header id="top-header">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
    <%= link_to "FE_ED", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">マイメニュー</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "投稿一覧", microposts_path, class: "nav-link active", aria: { current: "page" } %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿作成", new_micropost_path, class: "nav-link active", aria: { current: "page" } %>
          </li>
        <% end %>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><%= link_to "マイページ", current_user, class: "dropdown-item" %></li>
                <li>
                  <%= link_to"ログアウト", logout_path, data: { "turbo-method": :delete }, class: "dropdown-item" %>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "ログイン", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", signup_path, class: "btn btn-purple py-2" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if controller_name != 'sessions' %>
<div class="search_form pe-3">
  <%= search_form_for @q, url: search_path, class:"row justify-content-end" do |f| %>
  <div class="col-md-4 p-0">
    <%= f.search_field :content, class:"form-control" %>
  </div>
  <div class="col-md-1 p-0">
    <button class="btn btn-outline-success" type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
  </div>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--provideで設定したシンボル(:title)が引数として代入される-->
    <title><%= full_title(yield(:title)) %> | 基本情報フィードバックサイトFE_FD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-cache-control" content="no-cache">
    <!--以下４つは、スタイルシートとJsをインクルード（含める）ためのもの-->
    <!--SCRF対策-->
    <%= csrf_meta_tags %>
    <!--XSS対策-->
    <%= csp_meta_tag %>
    <!--application.cssを全てのメディアタイプで使用可能にする-->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <div id="flash">
        <%= render 'application/flash' %>
      <div>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>


    <%= turbo_frame_tag "modal" %>
    <div id="flashes" class="position-fixed top-0 end-0" style="margin: 0.75rem"></div>
  </body>
</html>

app/views/layouts/application.turbo_stream.erb
<% if flash[:notice] %>
  <%= turbo_stream.append("alerts") do %>
    <%= render "application/alert", type: :info, message: flash[:notice] %>
  <% end %>
<% end %>

<% if flash[:alert] %>
  <%= turbo_stream.append("alerts") do %>
    <%= render "application/alert", type: :warning, message: flash[:alert] %>
  <% end %>
<% end %>

<%= yield %>

app/views/microposts/_micropost.html.erb
<!--<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li

app/views/microposts/edit.html.erb
<%= provide(:title, "投稿編集") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @post) do |f| %>

      <%= f.label :content, "投稿詳細" %>
      <%= f.text_area :content %>

      <%= f.submit "編集内容を保存する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/microposts/index.html.erb
<%= provide(:title, "投稿一覧") %>

  <div class="container mt-5">
    <h1 class="mb-4">投稿一覧</h1>
    <div class="row">
        <% @posts.each do |micropost| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <h5 class="card-title"><%= micropost.user.name %></h5>
              <p class="card-text"><%= micropost.content %></p>
              <a href="<%= micropost_path(micropost) %>" class="btn btn-primary">詳細を見る</a>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @posts %>
    </div>
  </div>

app/views/microposts/new.html.erb
<%= provide(:title, '投稿作成')%>
<h1>投稿作成</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :content, "本文" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit "投稿する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/microposts/show.html.erb
<%= provide(:title, @post.user.name + "の投稿") %>

<div class="container mt-5">
  <h1 class="mb-4"><%= @post.user.name %>の投稿</h1>
  <div class="card mb-4 shadow-sm">
    <div class="card-body">
      <div class="card-text">
        <%= @post.content %>
      </div>
    </div>
  </div>

  <div class="btn-group" role="group" aria-label="Button group">
    <% if current_user == @post.user %>
      <%= link_to '編集', edit_micropost_path, class: 'btn btn-primary' %>
      <%= link_to "削除", @post, class: 'btn btn-danger' ,
                                data: { "turbo-method": :delete,
                                turbo_confirm: "本当に削除してよろしいですか?" } %>
    <% end %>
    <div><%= link_to '戻る', microposts_path, class: 'btn btn-secondary' %></div>
    <div><%= render 'favorites/favorite', post: @post %></div>
  </div>
</div>

app/views/microposts/update.turbo_stream.erb
<%= turbo_stream.replace @post %>
<%= turbo_stream_flash %>

app/views/shared/_error_messages.html.erb
<!--入力内容に問題があった際のエラー文を出力する-->
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "エラー") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<%= provide(:title, "お問い合わせ") %>
<body>
<%= link_to("トップページ", root_path) %>
</body>

app/views/static_pages/help.html.erb
<%= provide(:title, "利用規約") %>
<body>
<%= link_to"トップページ", root_path %>
</body>

app/views/static_pages/home.html.erb
<%= provide(:title, "ホーム") %>

<div class="container text-center mt-5">
<%= image_tag 'home.png', class: 'img-fluid rounded', alt: 'Description of image' %>
  <!--<%= render "layouts/carousel" %>-->

  <h5 class="my-4">FE_EDってどんなサービス？</h5>
  <p class="mb-4">
    FE_EDでは、基本情報技術者試験を目指すエンジニアのために<br>
    過去の受講生が経験し、得た知識を残すフィードバックサイトです。
  </p>

  <div class="d-lg-flex align-items-center justify-content-center mb-5">
    <div class="d-flex flex-column align-items-center mb-3 mb-lg-0 me-3">
      <%= image_tag "book_gijutsusyo_web.png", alt: "", width: "200", height: "200", class: "rounded-circle mx-auto" %>
      <p class="mt-2">優秀な教材<br>学習サイトを共有</p>
    </div>
    <div class="d-flex flex-column align-items-center mb-3 mb-lg-0 me-3">
      <%= image_tag "computer_tokui_boy.png", alt: "", width: "200", height: "200", class: "rounded-circle mx-auto" %>
      <p class="mt-2">これまで受講してきた<br>仲間の経験談を学習に活かせる</p>
    </div>
    <div class="d-flex flex-column align-items-center mb-3 mb-lg-0 me-3">
      <%= image_tag "juken_goukakuhappyou_happy.png", alt: "", width: "200", height: "200", class: "rounded-circle mx-auto" %>
      <p class="mt-2">最短合格<br>資格取得でエンジニアを目指そう！</p>
    </div>
  </div>

  <h5 class="my-4">FE_EDを始める</h5>

  <div class="mb-4">
    <%= link_to "新規登録", signup_path, class: "btn btn-success me-2" %>
    <%= link_to "ログイン", login_path, class: "btn btn-secondary" %>
  </div>

</div>

app/views/static_pages/policy.html.erb
<%= provide(:title, "プライバシーポリシー") %>
<body>
<%= link_to"トップページ", root_path %>
</body>

app/views/users/edit.html.erb
<% provide(:title, "個人情報") %>
<h1>個人情報</h1>
<div class="row">
  <div class="col-md-">
    <%= render "layouts/form" %>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, '新規登録') %>
<section class="position-relative py-5 my-5 overflow-hidden bg-new">
  <div class="d-none d-md-block position-absolute top-0 start-0 bg-primary w-100 h-100"></div>
  <div class="d-md-none position-absolute top-0 start-0 bg-primary w-100 h-100"></div>
  <div class="container position-relative mx-auto">
    <div class="row align-items-center">
      <div class="col-12 col-md-8 col-lg-5 mb-5">
        <div>
          <h2 class="display-4 fw-bold mb-4 text-white">ゴードービジネスマシン<br>
          コミュニティに参加して<br>貴方が培った経験を<br>共有しませんか？</h2>
          <p class="mb-0 text-white"></p>
        </div>
      </div>
      <div class="col-12 col-md-10 col-lg-5 ms-auto">
        <div class="p-5 bg-light rounded text-center">
            <span class="text-muted">サインイン</span>
            <h3 class="fw-bold mb-5">コミュニティに参加する</h3>
            <%= form_with(model: @user) do |f| %>
              <%= render 'shared/error_messages' %>
              <%= f.label :name, "お名前" %>
              <%= f.text_field :name, class: 'form-control mb-2', placeholder: "ゴードー太郎" %>
              <%= f.label :email, "メールアドレス" %>
              <%= f.email_field :email, class: 'form-control mb-2', placeholder: "@example.com" %>
              <%= f.label :password, "パスワード" %>
              <%= f.password_field :password, class: 'form-control mb-2', placeholder: "パスワード" %>
              <%= f.label :password_confirmation, "パスワード再確認" %>
              <%= f.password_field :password_confirmation, class: 'form-control mb-2', placeholder: "パスワード" %>
              <%= f.submit "始める", class: "btn btn-purple py-2 w-100 mb-4" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0"><%= @user.name %>の詳細</h2>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
              <p><strong>ユーザー名:</strong> <%= @user.name %></p>
              <p><strong>メールアドレス:</strong> <%= @user.email %></p>
              <p><strong>登録日:</strong> <%= @user.created_at.strftime("%Y年%m月%d日") %></p>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to '編集', edit_user_path(@user), class: 'btn btn-warning' if current_user == @user %>
          <%= link_to '戻る', microposts_path, class: 'btn btn-secondary' %>
            | <%= link_to "削除", @user, class: 'btn btn-danger' ,
                                        data: { "turbo-method": :delete,
                                        turbo_confirm: "本当に削除してよろしいですか?" }  if current_user == @user%>

        </div>
      </div>
    </div>
  </div>
</div>